schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true

jobs:
- job: Build_Kaiju
  variables:
    CCACHE_DIR: $(Pipeline.Workspace)/cache
    GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
    AUTOCATS_DIR: $(Pipeline.Workspace)/autocats
    GRADLE_VERSION: gradle-6.9
    GRADLE_URL: https://services.gradle.org/distributions/$(GRADLE_VERSION)-bin.zip
    GRADLE_INSTALL_DIR: $(Pipeline.Workspace)/gradle
    Z3_VERSION: z3-4.8.12
  strategy:
    matrix:
      ghidra-git:
        ghidraVersion: "master"
      ghidra1011:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.1_build/ghidra_10.1.1_PUBLIC_20211221.zip"
        ghidraVersion: "10.1.1"
      ghidra101:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1_build/ghidra_10.1_PUBLIC_20211210.zip"
        ghidraVersion: "10.1"
      ghidra1004:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.4_build/ghidra_10.0.4_PUBLIC_20210928.zip"
        ghidraVersion: "10.0.4"
      ghidra1003:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.3_build/ghidra_10.0.3_PUBLIC_20210908.zip"
        ghidraVersion: "10.0.3"
      ghidra1002:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.2_build/ghidra_10.0.2_PUBLIC_20210804.zip"
        ghidraVersion: "10.0.2"
      ghidra1001:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.1_build/ghidra_10.0.1_PUBLIC_20210708.zip"
        ghidraVersion: "10.0.1"
      ghidra100:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0_build/ghidra_10.0_PUBLIC_20210621.zip"
        ghidraVersion: "10.0"
      ghidra924:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_9.2.4_build/ghidra_9.2.4_PUBLIC_20210427.zip"
        ghidraVersion: "9.2.4"
      ghidra923:
        ghidraUrl: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_9.2.3_build/ghidra_9.2.3_PUBLIC_20210325.zip"
        ghidraVersion: "9.2.3"
      ghidra922:
        ghidraUrl: "https://ghidra-sre.org/ghidra_9.2.2_PUBLIC_20201229.zip"
        ghidraVersion: "9.2.2"
      ghidra921:
        ghidraUrl: "https://ghidra-sre.org/ghidra_9.2.1_PUBLIC_20201215.zip"
        ghidraVersion: "9.2.1"
      ghidra92:
        ghidraUrl: "https://ghidra-sre.org/ghidra_9.2_PUBLIC_20201113.zip"
        ghidraVersion: "9.2"
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:

  - bash: |
      set -e
      sudo apt-get -y update
      sudo apt-get install ccache -y
      echo "##vso[task.prependpath]/usr/lib/ccache"
    displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc

  - task: Cache@2
    inputs:
      key: 'ccache | "$(System.JobDisplayName)" ' # Same for each version of Ghidra more or less
      restoreKeys: 'ccache'
      path: $(CCACHE_DIR)
    displayName: ccache

  - script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
      echo "##vso[task.prependpath]$(JAVA_HOME_11_X64)/bin:$(PATH)"
    displayName: "Set java version"

  - task: Cache@2
    inputs:
      key: '"$(Z3_VERSION)" | z3'
      path: $(Pipeline.Workspace)/z3
    displayName: Cache z3 dir

  - task: Cache@2
    condition: and(succeeded(), ne(variables['ghidraUrl'], ''))
    inputs:
      key: '"$(ghidraUrl)" | binary'
      path: $(Pipeline.Workspace)/zip
    displayName: Cache ghidra binary

  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | "$(System.JobDisplayName)" '
      restoreKeys: gradle
      path: $(GRADLE_USER_HOME)
    displayName: Gradle build cache
  - task: Cache@2
    inputs:
      key: '"$(AUTOCATS_DIR)" | autocats'
      path: $(AUTOCATS_DIR)
    displayName: Cache AUTOCATS

  - task: Cache@2
    inputs:
      key: '"$(GRADLE_URL)" | gradle'
      path: $(GRADLE_INSTALL_DIR)
    displayName: Cache Gradle 6.x

  - bash: |
      set -e
      sudo apt-get -y install ninja-build
      test -d $(Pipeline.Workspace)/z3 || git clone -b $(Z3_VERSION) --depth 1 https://github.com/Z3Prover/z3.git z3
      mkdir -p z3/build
      cd z3/build
      cmake -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DZ3_BUILD_JAVA_BINDINGS=On ..
      ninja install
    condition: succeeded()
    workingDirectory: $(Pipeline.Workspace)
    displayName: Build Z3

  - bash: |
      set -e
      test -d zip || (mkdir zip && cd zip && wget $(ghidraUrl))
      unzip zip/*.zip
    condition: and(succeeded(), ne(variables['ghidraUrl'], ''))
    workingDirectory: $(Pipeline.Workspace)
    displayName: Download Ghidra binary from $(ghidraUrl)
  - bash: |
      set -e
      sudo apt-get -y install bison flex xvfb
      git clone --depth 1 https://github.com/NationalSecurityAgency/ghidra
    condition: and(succeeded(), eq(variables['ghidraUrl'], ''))
    workingDirectory: $(Pipeline.Workspace)
    displayName: Download and build Ghidra from git part 1

  - task: Cache@2
    displayName: Cache Ghidra dependencies
    inputs:
      key: 'gradle deps'
      path: $(Pipeline.Workspace)/ghidra/dependencies
    condition: and(succeeded(), eq(variables['ghidraUrl'], ''))

  - bash: |
      echo "##vso[task.prependpath]$(GRADLE_INSTALL_DIR)/$(GRADLE_VERSION)/bin"
      test -d $(GRADLE_INSTALL_DIR) && exit 0
      wget $(GRADLE_URL) -O gradle.zip
      unzip -d $(GRADLE_INSTALL_DIR) gradle.zip
      rm gradle.zip
    workingDirectory: $(Pipeline.Workspace)
    displayName: Download gradle 6.x binary from $(GRADLE_URL)
  - bash: |
      set -ex
      cd ghidra
      gradle --build-cache --init-script gradle/support/fetchDependencies.gradle init
      gradle --build-cache buildGhidra -x ip
      mkdir -p $(Pipeline.Workspace)/zip
      cp build/dist/*.zip $(Pipeline.Workspace)/zip/
      cd $(Pipeline.Workspace)
      unzip zip/*.zip
    condition: and(succeeded(), eq(variables['ghidraUrl'], ''))
    workingDirectory: $(Pipeline.Workspace)
    displayName: Download and build Ghidra from git part 2
  - bash: |
      set -e
      Z3CLASSPATH=$(Pipeline.Workspace)/z3/build GHIDRA_INSTALL_DIR=$(find $(Pipeline.Workspace) -maxdepth 1 -type d -name 'ghidra_*') gradle --build-cache
    displayName: Build Kaiju extension and plugins
    workingDirectory: .
  - bash: |
      test -d $AUTOCATS_DIR || git clone https://github.com/cmu-sei/autocats $AUTOCATS_DIR
    displayName: Download AUTOCATS
  - bash: |
      set -e
      # Needs a head
      Xvfb :1 &
      echo $AUTOCATS_DIR
      DISPLAY=:1 Z3CLASSPATH=$(Pipeline.Workspace)/z3/build GHIDRA_INSTALL_DIR=$(find $(Pipeline.Workspace) -maxdepth 1 -type d -name 'ghidra_*') gradle -PKAIJU_AUTOCATS_DIR=$AUTOCATS_DIR --build-cache test
      kill %%
    displayName: Run Kaiju tests
    workingDirectory: .
  - script: gradle --stop
  - publish: dist/
  - task: GitHubRelease@0
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    inputs:
      gitHubConnection: gh
      repositoryName: $(Build.Repository.Name)
      action: delete
      tagSource: manual
      tag: ghidra-$(ghidraVersion)
    continueOnError: true
  - task: DownloadSecureFile@1
    condition: eq(variables['Build.SourceBranchName'], 'main')
    name: deployKey
    inputs:
      secureFile: 'deploy.key'
  - bash: |
      mkdir -p ~/.ssh
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      chmod og-r $(deployKey.secureFilePath)
      ssh-add $(deployKey.secureFilePath)
      git config --global user.email "eschwartz@cert.org"
      git config --global user.name "eschwartz"
      git remote add ssh-origin git@github.com:sei-eschwartz/kaiju.git
      git push --delete ssh-origin ghidra-$(ghidraVersion)
      rm -f $(deployKey.secureFilePath)
    condition: eq(variables['Build.SourceBranchName'], 'main')
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    continueOnError: true
    displayName: Delete old git tag ghidra-$(ghidraVersion)
  - task: GitHubRelease@0
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    inputs:
      gitHubConnection: gh
      repositoryName: $(Build.Repository.Name)
      action: create
      target: $(Build.SourceVersion)
      tagSource: manual
      tag: ghidra-$(ghidraVersion)
      title: CERT Kaiju binary analysis extension for Ghidra $(ghidraVersion)
      assets: dist/*.zip
      addChangeLog: false
